#!/usr/bin/env node
// Generated by toolfactory. Do not edit; run `toolfactory build` to regenerate.
import { Command } from "commander";
import { z } from "zod";
import { operations as authored } from "../ops.js";
import { context } from "./config.js";
import { serves } from "./types.js";
import { web } from "./web.js";

/** The authored operations plus the generated `web` one, exactly as the MCP kernel lists them. */
const operations = [...authored, web];

const program = new Command()
  .name("vutoolkit")
  .description("Universal toolkit for Vanderbilt student life - OneVU SSO and passkey sessions, what-if grades, YES tools; built for AI agents first.")
  .version("0.1.1");

for (const op of operations) {
  if (!serves(op, "cli")) continue;
  const command = program.command(op.name).description(op.description);
  command.option("--json <arguments>", "all arguments as one JSON object");
  const schema = z.toJSONSchema(op.input, { io: "input" }) as {
    properties?: Record<string, { description?: string; type?: string; default?: unknown }>;
  };
  for (const [key, property] of Object.entries(schema.properties ?? {})) {
    const flag = property.type === "boolean" ? `--${key}` : `--${key} <value>`;
    const hint = property.type === "array" ? " (comma-separated)" : property.type === "object" ? " (JSON)" : "";
    command.option(flag, `${property.description ?? key}${hint}`);
  }
  command.action(async (options: Record<string, string | boolean | undefined>) => {
    const fromJson = options.json ? (JSON.parse(String(options.json)) as Record<string, unknown>) : {};
    const fromFlags = Object.fromEntries(
      Object.entries(options)
        .filter(([key, value]) => key !== "json" && value !== undefined)
        .map(([key, value]) => {
          const type = schema.properties?.[key]?.type;
          if (type === "number" || type === "integer") return [key, Number(value)];
          if (type === "boolean") return [key, value === true || value === "true"];
          if (type === "array") return [key, String(value).split(",").map((item) => item.trim()).filter(Boolean)];
          if (type === "object") return [key, JSON.parse(String(value))];
          return [key, value];
        }),
    );
    const args = op.input.parse({ ...fromJson, ...fromFlags });
    const result = await op.handler(args as never, context());
    process.stdout.write(`${JSON.stringify(result, null, 2)}\n`);
  });
}

program
  .command("mcp")
  .description("Serve the operations as an MCP server over stdio, or over streamable HTTP with --http")
  .option(
    "--http [port]",
    "serve over MCP streamable HTTP instead of stdio (default port 3000, host 127.0.0.1, path /mcp)",
  )
  .option(
    "--pair",
    "serve over HTTP with a fresh pairing token: prints <url>#<token> and requires it as a bearer token",
  )
  .option("--open", "serve over HTTP and open the web app in this machine's browser")
  .action(async (options: { http?: string | boolean; pair?: boolean; open?: boolean }) => {
    const { serve, serveHttp } = await import("./mcp.js");
    if (options.http === undefined && !options.pair && !options.open) await serve();
    else {
      const port = options.http === undefined || options.http === true ? 3000 : Number(options.http);
      await serveHttp({ port, pair: options.pair, open: options.open });
    }
  });

program.parseAsync(process.argv).catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
