// Generated by toolfactory. Do not edit; run `toolfactory build` to regenerate.
import { homedir } from "node:os";
import { join } from "node:path";
import type { Context } from "./types.js";

/**
 * Where this tool may keep its own state: VUTOOLKIT_DATA_DIR when a host sets it, else the
 * platform's own data location (XDG on POSIX, %LOCALAPPDATA% on Windows).
 */
function dataDir(): string {
  // Hosts that launch the kernel export their own name for it: Agent Plugins clients and
  // OpenClaw set PLUGIN_DATA, Claude Code sets CLAUDE_PLUGIN_DATA.
  const configured =
    process.env["VUTOOLKIT_DATA_DIR"] ??
    process.env.PLUGIN_DATA ??
    process.env.CLAUDE_PLUGIN_DATA;
  if (configured) return configured;
  const base =
    process.platform === "win32"
      ? (process.env.LOCALAPPDATA ?? join(homedir(), "AppData", "Local"))
      : (process.env.XDG_DATA_HOME ?? join(homedir(), ".local", "share"));
  return join(base, "vutoolkit");
}

/** Configuration is read from the environment; hosts inject it from their own settings UI. */
export function context(): Context {
  return {
    config: {

    },
    dataDir: dataDir(),
  };
}
