// Generated by toolfactory. Do not edit; run `toolfactory build` to regenerate.
import { spawn } from "node:child_process";
import { extname } from "node:path";
import { fileURLToPath } from "node:url";
import { z } from "zod";
import { operation } from "./types.js";

/** The kernel beside this file, in the form that is running: `.ts` under tsx, `.js` from dist. */
const KERNEL = fileURLToPath(
  new URL(`./mcp${extname(fileURLToPath(import.meta.url))}`, import.meta.url),
);
const SERVING = /Serving MCP streamable HTTP on (\S+)/;

export const web = operation({
  name: "web",
  description:
    "Open this tool's web app: serves the operations page and the MCP endpoint on a free local port, opens a browser there, and returns the URL.",
  input: z.object({}),
  output: z.object({ url: z.string() }),
  requires: ["shell", "net"],
  annotations: { openWorldHint: false },
  handler: () =>
    new Promise<{ url: string }>((resolve, reject) => {
      const child = spawn(process.execPath, [...process.execArgv, KERNEL, "--http", "0", "--open"], {
        detached: true,
        stdio: ["ignore", "ignore", "pipe"],
      });
      let output = "";
      child.on("error", reject);
      child.on("exit", (code) => reject(new Error(`the kernel exited with ${code}: ${output}`)));
      child.stderr.setEncoding("utf8");
      child.stderr.on("data", (chunk: string) => {
        output += chunk;
        const serving = SERVING.exec(output);
        if (!serving) return;
        // The child outlives this process; unref both handles so neither keeps it alive, and
        // leave the pipe open so the kernel's own stderr never writes to a closed one.
        child.unref();
        (child.stderr as unknown as { unref: () => void }).unref();
        // The page, not the endpoint, and without the token the child already handed the browser:
        // an operation's result travels through an agent, and a token is a credential.
        resolve({ url: new URL("/", serving[1]).href });
      });
    }),
});
