import { searchProfessors } from "./professors.js";
import { z } from "zod";
import { operation, type Context } from "../toolfactory/types.js";
import { sessionStore } from "../vault/file-store.js";
import { credentialEnv } from "../vault/credential-store.js";
import { ensureSession } from "../sso/ensure.js";
import { YesPlanningClient } from "./planning-client.js";
import { officialAuditGraph } from "./audit-graph.js";
import { buildDegreeGraph, parsePrerequisites } from "./planner.js";
import { solveSchedules, cartDifference } from "./scheduler.js";
import { plannerInputSchema, scheduleInputSchema, sectionSchema } from "./schemas.js";
async function withClient<T>(ctx: Context, read: (client: YesPlanningClient) => Promise<T>): Promise<T> {
  const store = sessionStore(ctx.dataDir, credentialEnv(ctx.config));
  await ensureSession("vanderbilt", store);
  const attempt = () => read(new YesPlanningClient({ cookies: store.cookies("vanderbilt") }));
  try { return await attempt(); }
  catch (error) {
    if (!(error instanceof Error) || !error.message.includes("session requires refresh")) throw error;
    await store.forget("vanderbilt");
    await ensureSession("vanderbilt", store);
    return attempt();
  }
}
const jsonObject = z.record(z.string(), z.unknown());
const readonly = { readOnlyHint: true, idempotentHint: true };
export const yesOperations = [
  operation({ name: "professors.search", description: "Look up public Vanderbilt Rate My Professors candidates and ratings. Preserves namesake ambiguity; no Vanderbilt credentials leave the toolkit.", input: z.object({ name: z.string().min(2) }), output: z.object({ professors: z.array(jsonObject), source: z.string(), fetchedAt: z.string(), note: z.string() }), requires: ["net"], annotations: readonly, handler: async ({ name }) => searchProfessors(name) }),
  operation({ name: "degree.audit", description: "Read Vanderbilt's official degree-audit requirement groups, status, counters and existing planner courses. No audit refresh, enrollment or planner mutation; report timestamps are preserved.", input: z.object({}), output: z.object({ audits: z.array(jsonObject), plannerCourses: z.array(jsonObject), source: z.literal("live"), fetchedAt: z.string() }), requires: ["net", "secret"], annotations: readonly, handler: async (_, ctx) => withClient(ctx, (c) => c.degreeAudit()) }),
  operation({ name: "degree.graph", description: "Build a directed graph from the authenticated student's official YES audit, including all current requirement groups/lines, satisfying courses and optional planner courses. Official course alternatives load separately via degree.options; this does not invent degree rules.", input: z.object({}), output: z.object({ nodes: z.array(z.unknown()), edges: z.array(z.unknown()), source: z.literal("live"), fetchedAt: z.string(), alternativesLoaded: z.boolean(), note: z.string() }), requires: ["net", "secret"], annotations: readonly, handler: async (_, ctx) => officialAuditGraph(await withClient(ctx, (c) => c.degreeAudit())) }),
  operation({ name: "degree.options", description: "Read all official course satisfiers for one current degree-audit requirement line. Report and entry IDs come from degree.audit/degree.graph; the student identity is resolved internally from the authenticated audit.", input: z.object({ reportSequence: z.number().int(), entrySequence: z.number().int() }), output: z.object({ courses: z.array(jsonObject), source: z.literal("live") }), requires: ["net", "secret"], annotations: readonly, handler: async ({ reportSequence, entrySequence }, ctx) => ({ courses: await withClient(ctx, (c) => c.courseSatisfiers(reportSequence, entrySequence)), source: "live" as const }) }),
  operation({ name: "courses.search", description: "Search the live YES catalog for course IDs, titles, schools and typical offerings. Vanderbilt's keyword search can return broad matches; select by returned course code.", input: z.object({ keywords: z.string().min(3) }), output: z.object({ courses: z.array(jsonObject), source: z.literal("live") }), requires: ["net", "secret"], annotations: readonly, handler: async ({ keywords }, ctx) => withClient(ctx, (c) => c.searchCourses(keywords)) }),
  operation({ name: "courses.detail", description: "Read official YES course description and prerequisite text, preserving ambiguous prose as unknown instead of guessing. Course ID and offer number come from courses.search or the official planner.", input: z.object({ id: z.string().regex(/^\d+$/), offerNumber: z.number().int().positive().default(1) }), output: z.object({ id: z.string(), offerNumber: z.number(), text: z.string(), description: z.string().nullable(), prerequisiteText: z.string().nullable(), prerequisites: z.unknown(), source: z.string() }), requires: ["net", "secret"], annotations: readonly, handler: async ({ id, offerNumber }, ctx) => { const result = await withClient(ctx, (c) => c.courseDetail(id, offerNumber)); return { ...result, prerequisites: result.prerequisiteText === null ? { kind: "unknown", text: "No prerequisite field found; verify the official catalog" } : parsePrerequisites(result.prerequisiteText) }; } }),
  operation({ name: "courses.sections", description: "Read live YES section alternatives with campus-local meeting times, professor, room, availability and lecture/lab component. Missing or TBA times are explicit. No cart/enrollment changes.", input: z.object({ keywords: z.string().min(3), termCode: z.string().regex(/^\d+$/).optional() }), output: z.object({ sections: z.array(sectionSchema), source: z.literal("live") }), requires: ["net", "secret"], annotations: readonly, handler: async ({ keywords, termCode }, ctx) => withClient(ctx, (c) => c.searchSections(keywords, termCode)) }),
  operation({ name: "scheduler.solve", description: "Enumerate conflict-free section combinations; include labs, multiple meetings, course exclusions and preferred break times. Deterministic preference ranking and explicit truncation/TBA uncertainty. Returns choices, never enrollment actions.", input: scheduleInputSchema, output: z.object({ schedules: z.array(jsonObject), found: z.number(), searched: z.number(), truncated: z.boolean(), searchComplete: z.boolean(), incompatibleGroups: z.array(z.array(z.string())), excludedCourses: z.array(z.string()), excludedSectionIds: z.array(z.string()), warnings: z.array(z.string()) }), annotations: readonly, handler: async (args) => solveSchedules(args) }),
  operation({ name: "scheduler.cartPlan", description: "Pure cart-only add/remove diff for a selected schedule. Unselected or unrelated courses are retained by default. Does not execute any requests or alter enrollment.", input: z.object({ currentIds: z.array(z.string()), chosen: z.array(sectionSchema), candidates: z.array(sectionSchema), keepExcluded: z.boolean().default(true), preserveSectionIds: z.array(z.string()).default([]) }), output: z.object({ add: z.array(z.string()), remove: z.array(z.string()), unchanged: z.array(z.string()) }), annotations: readonly, handler: async ({ currentIds, chosen, candidates, keepExcluded, preserveSectionIds }) => cartDifference(currentIds, chosen, candidates, keepExcluded, preserveSectionIds) }),
  operation({ name: "planner.graph", description: "Deterministically rank paths for supplied official requirement alternatives and/or course goals. Shared prerequisites count once; completed and planned work is factored in. Unknown prose, missing metadata, cycles and truncation remain explicit. A model-optimal result is exhaustive only for supplied inputs; degree.audit remains the official authority.", input: plannerInputSchema, output: z.object({ nodes: z.array(z.unknown()), edges: z.array(z.unknown()), alternatives: z.array(jsonObject), truncated: z.boolean(), warnings: z.array(z.string()), modelOptimal: z.boolean(), rankingScope: z.string(), ranking: z.string() }), annotations: readonly, handler: async (args) => buildDegreeGraph(args) }),
];
