import { z } from "zod";
import type { RequirementExpression } from "./planner.js";
export const meetingSchema = z.object({ days: z.array(z.string().regex(/^[MTWRFSU]$/)), start: z.number().min(0).max(1439), end: z.number().min(1).max(1440), location: z.string().optional() }).refine((meeting) => meeting.end > meeting.start, "Meeting end must follow its start");
export const sectionSchema = z.object({ id: z.string().min(1), course: z.string().min(1), section: z.string(), component: z.string(), termCode: z.string().optional(), title: z.string().optional(), credits: z.number().nonnegative().optional(), instructors: z.array(z.string()).optional(), meetings: z.array(meetingSchema), timeUnknown: z.boolean().optional(), availability: z.string().optional(), compatibleWith: z.array(z.string()).optional() });
export const scheduleInputSchema = z.object({ sections: z.array(sectionSchema), excludedCourses: z.array(z.string()).optional(), excludedSectionIds: z.array(z.string()).optional(), blockedTimes: z.array(meetingSchema).optional(), hidePreferenceConflicts: z.boolean().optional(), limit: z.number().int().positive().optional(), maxSearchNodes: z.number().int().positive().optional() });
export const prerequisiteSchema: z.ZodType<RequirementExpression> = z.lazy(() => z.union([z.object({ kind: z.literal("course"), course: z.string() }), z.object({ kind: z.enum(["all", "any"]), items: z.array(prerequisiteSchema) }), z.object({ kind: z.literal("unknown"), text: z.string() })]));
export const plannerCourseSchema = z.object({ course: z.string(), title: z.string().optional(), credits: z.number().nonnegative().optional(), prerequisites: prerequisiteSchema.optional(), description: z.string().optional(), typicallyOffered: z.string().optional(), instructors: z.array(z.string()).optional(), rating: z.object({ average: z.number().min(0).max(5), count: z.number().int().nonnegative(), url: z.string().url() }).optional(), sourceUrl: z.string().url().optional() });
export const plannerRequirementSchema = z.object({ id: z.string().min(1), label: z.string().optional(), expression: prerequisiteSchema, satisfied: z.boolean().optional() });
export const plannerInputSchema = z.object({ courses: z.array(plannerCourseSchema), completed: z.array(z.string()).optional(), planned: z.array(z.string()).optional(), goals: z.array(z.string()).optional(), requirements: z.array(plannerRequirementSchema).optional(), preferences: z.record(z.string(), z.number().finite()).optional(), maxAlternatives: z.number().int().positive().optional() });
