// Generated by toolfactory. Do not edit; run `toolfactory build` to regenerate.
import App from "@web/App";
import "../../utils/page.css";
import { mount, Pairing } from "../../utils/page";

mount(
  <>
    <div style={{ display: "flex", alignItems: "center" }}>
      <Pairing />
    </div>
    <App />
  </>,
);
