// Generated by toolfactory. Do not edit; run `toolfactory build` to regenerate.
/**
 * The generated router, in memory: `@webext-core/fake-browser` stands in for the extension APIs
 * and `fetch` is the only thing stubbed, so what is under test is the pairing store and the one
 * privileged call to the kernel.
 */
import { beforeEach, describe, expect, it, vi } from "vitest";
import { fakeBrowser } from "wxt/testing/fake-browser";
import { route } from "../entrypoints/background";

const OPERATION = "gpa.verify";
const ENVELOPE = JSON.stringify({
  jsonrpc: "2.0",
  id: 1,
  result: { structuredContent: { ok: true } },
});

describe("the background router", () => {
  beforeEach(() => {
    fakeBrowser.reset();
    vi.restoreAllMocks();
  });

  it("pairs from <url>#<token> and reports what it holds", async () => {
    expect(await route({ type: "pair", pairing: "http://127.0.0.1:4242/mcp#s3cret" })).toEqual({
      endpoint: "http://127.0.0.1:4242/mcp",
      token: true,
    });
    expect(await route({ type: "paired" })).toEqual({
      endpoint: "http://127.0.0.1:4242/mcp",
      token: true,
    });
  });

  it("calls the paired kernel with the MCP headers and the bearer token", async () => {
    const fetch = vi.spyOn(globalThis, "fetch").mockResolvedValue(new Response(ENVELOPE));
    await route({ type: "pair", pairing: "http://127.0.0.1:4242/mcp#s3cret" });
    const result = await route({
      type: "mcp",
      request: { method: "tools/call", params: { name: OPERATION } },
    });
    expect(result).toEqual({ ok: true });
    const [url, init] = fetch.mock.calls[0] as [string, RequestInit];
    expect(url).toBe("http://127.0.0.1:4242/mcp");
    expect(init.headers).toMatchObject({
      "Mcp-Method": "tools/call",
      "Mcp-Name": OPERATION,
      Authorization: "Bearer s3cret",
    });
  });

  it("says which endpoint refused when the kernel is not running", async () => {
    vi.spyOn(globalThis, "fetch").mockRejectedValue(new TypeError("Failed to fetch"));
    await expect(
      route({ type: "mcp", request: { method: "tools/call", params: { name: OPERATION } } }),
    ).rejects.toThrow(`${"http://127.0.0.1:3000/mcp"} refused the connection`);
  });
});
