// Generated by toolfactory. Do not edit; run `toolfactory build` to regenerate.
/**
 * The keyless end-to-end: the built `chrome-mv3` output is side-loaded into a real Chromium and
 * driven the way a human drives it — the options page takes the pairing string, the popup renders
 * the operation, and Run reaches a mock kernel on loopback through the background worker, which
 * is the only context holding the token. No LLM, no store credentials, no real session.
 *
 * Run `npm --prefix hosts/browser run build` first; this loads `.output/chrome-mv3`.
 */
import { mkdtempSync, rmSync } from "node:fs";
import { createServer } from "node:http";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { chromium } from "playwright";

const extension = fileURLToPath(new URL("../.output/chrome-mv3", import.meta.url));
const CASE = {"name":"gpa.verify","arguments":{}};
const TOKEN = "smoke-token";
const MARKER = "vutoolkit-browser-smoke";

const seen = [];
const kernel = createServer((request, response) => {
  let body = "";
  request.on("data", (chunk) => {
    body += chunk;
  });
  request.on("end", () => {
    seen.push({ headers: request.headers, body: JSON.parse(body || "{}") });
    response.writeHead(200, { "content-type": "application/json" });
    response.end(
      JSON.stringify({ jsonrpc: "2.0", id: 1, result: { structuredContent: { smoke: MARKER } } }),
    );
  });
});
await new Promise((resolve) => kernel.listen(0, "127.0.0.1", resolve));
const endpoint = `http://127.0.0.1:${kernel.address().port}/mcp`;

const profile = mkdtempSync(join(tmpdir(), "vutoolkit-browser-"));
// `channel: "chromium"` is the full build; the headless shell cannot side-load an extension.
const context = await chromium.launchPersistentContext(profile, {
  channel: "chromium",
  args: [`--disable-extensions-except=${extension}`, `--load-extension=${extension}`],
});
const failures = [];
context.on("weberror", (error) => failures.push(error.error().message));
try {
  const worker = context.serviceWorkers()[0] ?? (await context.waitForEvent("serviceworker"));
  const id = new URL(worker.url()).host;
  console.log(`PASS the extension loaded as ${id}`);

  const options = await context.newPage();
  await options.goto(`chrome-extension://${id}/options.html`);
  await options.locator("#pairing").fill(`${endpoint}#${TOKEN}`);
  await options.getByRole("button", { name: "Pair" }).click();
  await options.locator('[data-slot="paired"]').filter({ hasText: endpoint }).waitFor();
  console.log(`PASS paired with ${endpoint}`);

  const popup = await context.newPage();
  await popup.goto(`chrome-extension://${id}/popup.html`);
  await popup.getByRole("button", { name: CASE.name, exact: true }).click();
  for (const [name, value] of Object.entries(CASE.arguments)) {
    if (typeof value === "string") await popup.locator(`[id="${CASE.name}-${name}"]`).fill(value);
  }
  console.log(`PASS the popup renders the ${CASE.name} form`);

  await popup.getByRole("button", { name: "Run" }).click();
  await popup.getByRole("tab", { name: "Result" }).click();
  const result = popup.locator('pre[data-slot="result"]');
  await result.waitFor({ state: "visible" });
  const text = (await result.textContent()).trim();
  if (!text.includes(MARKER)) throw new Error(`the popup rendered no result: ${text}`);
  console.log(`PASS ${CASE.name} answered through the worker: ${text.replace(/\s+/g, " ")}`);

  const call = seen.at(-1);
  if (!call) throw new Error("the mock kernel was never called");
  if (call.headers.authorization !== `Bearer ${TOKEN}`) {
    throw new Error(`the worker sent no bearer token: ${call.headers.authorization}`);
  }
  if (call.body.params?.name !== CASE.name) {
    throw new Error(`the worker called ${call.body.params?.name}, not ${CASE.name}`);
  }
  console.log(`PASS the worker sent Bearer <token> and Mcp-Name: ${call.headers["mcp-name"]}`);

  if (failures.length) throw new Error(`the extension raised: ${failures.join("; ")}`);
  console.log("PASS no uncaught page errors");
} finally {
  await context.close();
  kernel.close();
  rmSync(profile, { recursive: true, force: true });
}
