// Generated by toolfactory. Do not edit; run `toolfactory build` to regenerate.
import App from "@web/App";
import "../../utils/page.css";
import { mount, OpenFullPage, Pairing } from "../../utils/page";

mount(
  <>
    <div style={{ display: "flex", alignItems: "center" }}>
      <Pairing />
      <OpenFullPage />
    </div>
    <App />
  </>,
);
