// Generated by toolfactory. Do not edit; run `toolfactory build` to regenerate.
import { getToolPluginMetadata } from "openclaw/plugin-sdk/tool-plugin";
import type { OpenClawPluginApi } from "openclaw/plugin-sdk/plugin-entry";
import { describe, expect, it } from "vitest";
import entry from "./index.js";

describe("vutoolkit", () => {
  it("declares tool metadata", () => {
    expect(getToolPluginMetadata(entry)?.tools.map((tool) => tool.name)).toEqual(["gpa.verify","grades.whatif","record.fetch","sessions.ensure","sessions.forget","sessions.ingest","sessions.list","sessions.open","sessions.refresh","web"]);
  });

  it("serves the web app as a Control UI tab", () => {
    const registered: Record<string, unknown[]> = {};
    const record = (name: string) => (value: unknown) => {
      (registered[name] ??= []).push(value);
    };
    const api = {
      registerTool: record("registerTool"),
      registerHttpRoute: record("registerHttpRoute"),
      registerControlUiDescriptor: record("registerControlUiDescriptor"),
    } as Partial<OpenClawPluginApi>;

    entry.register(api as OpenClawPluginApi);

    expect(registered.registerHttpRoute).toEqual([
      expect.objectContaining({ path: "/plugins/vutoolkit/web", match: "prefix", auth: "gateway" }),
    ]);
    expect(registered.registerControlUiDescriptor).toEqual([
      expect.objectContaining({ surface: "tab", path: "/plugins/vutoolkit/web/" }),
    ]);
  });
});
