// Generated by toolfactory. Do not edit; run `toolfactory build` to regenerate.
import { getToolPluginMetadata } from "openclaw/plugin-sdk/tool-plugin";
import type { OpenClawPluginApi } from "openclaw/plugin-sdk/plugin-entry";
import { describe, expect, it } from "vitest";
import entry from "./index.js";

describe("vutoolkit", () => {
  it("declares tool metadata", () => {
    expect(getToolPluginMetadata(entry)?.tools.map((tool) => tool.name)).toEqual(["vutoolkit_courses_detail","vutoolkit_courses_search","vutoolkit_courses_sections","vutoolkit_degree_audit","vutoolkit_degree_graph","vutoolkit_degree_options","vutoolkit_gpa_verify","vutoolkit_grades_whatif","vutoolkit_graph_call","vutoolkit_planner_graph","vutoolkit_professors_search","vutoolkit_record_fetch","vutoolkit_scheduler_cartPlan","vutoolkit_scheduler_solve","vutoolkit_sessions_ensure","vutoolkit_sessions_forget","vutoolkit_sessions_ingest","vutoolkit_sessions_list","vutoolkit_sessions_open","vutoolkit_sessions_refresh","vutoolkit_setup_enroll","vutoolkit_setup_identity","vutoolkit_setup_prepare","vutoolkit_setup_run","vutoolkit_setup_status","vutoolkit_web"]);
  });

  it("serves the web app as a Control UI tab", () => {
    const registered: Record<string, unknown[]> = {};
    const record = (name: string) => (value: unknown) => {
      (registered[name] ??= []).push(value);
    };
    const api = {
      registerTool: record("registerTool"),
      registerHttpRoute: record("registerHttpRoute"),
      registerControlUiDescriptor: record("registerControlUiDescriptor"),
    } as Partial<OpenClawPluginApi>;

    entry.register(api as OpenClawPluginApi);

    expect(registered.registerHttpRoute).toEqual([
      expect.objectContaining({ path: "/plugins/vutoolkit/web", match: "prefix", auth: "gateway" }),
    ]);
    expect(registered.registerControlUiDescriptor).toEqual([
      expect.objectContaining({ surface: "tab", path: "/plugins/vutoolkit/web/" }),
    ]);
  });
});
