// tf:entry
// Generated by toolfactory. Do not edit; run `toolfactory build` to regenerate.
import { join } from "node:path";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { resolveStateDir } from "openclaw/plugin-sdk/state-paths";
import { Type } from "typebox";
import { operations } from "vutoolkit/dist/ops.js";
import { handler } from "vutoolkit/dist/toolfactory/mcp.js";
import type { OpenClawPluginApi } from "openclaw/plugin-sdk/plugin-entry";

/**
 * Where this tool may keep its own state: OpenClaw's state directory, one folder per plugin.
 * Lazy, so that importing this module resolves no path and touches no disk — every host loader
 * and `plugin-inspector check --runtime` import the entry long before any tool runs.
 */
const dataDir = () => join(resolveStateDir(), "plugin-data", "vutoolkit");

/** Fail loudly if the core package and this plugin ever disagree about the operation list. */
function operation(name: string) {
  const found = operations.find((candidate) => candidate.name === name);
  if (!found) throw new Error(`operation ${name} is missing from the core package`);
  return found;
}

const entry = defineToolPlugin({
  id: "vutoolkit",
  name: "Vutoolkit",
  description: "Universal toolkit for Vanderbilt student life - OneVU SSO and passkey sessions, what-if grades, YES tools; built for AI agents first.",
  activation: {
    "onStartup": true
  },
  tools: (tool) => [
    tool({
      name: "gpa.verify",
      description: "The golden anchor: recompute per-term GPAs from posted marks and compare against the numbers Vanderbilt posted. Run before trusting any what-if output. Defaults to the synthetic fixture; pass a live transcript to lock the real YES mapping.",
      parameters: Type.Unsafe({
        "type": "object",
        "properties": {
          "transcript": {
            "type": "object",
            "properties": {
              "terms": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "term": {
                      "type": "string"
                    },
                    "postedGpa": {
                      "type": "number"
                    },
                    "courses": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "course": {
                            "type": "string"
                          },
                          "credits": {
                            "type": "number"
                          },
                          "grade": {
                            "type": "string"
                          }
                        },
                        "required": [
                          "course",
                          "credits"
                        ]
                      }
                    }
                  },
                  "required": [
                    "term",
                    "courses"
                  ]
                }
              }
            },
            "required": [
              "terms"
            ]
          }
        }
      }),
      execute: async (params, config) =>
        operation("gpa.verify").handler(params as never, {
          config: config as Record<string, string | undefined>,
          dataDir: dataDir(),
        }),
    }),
    tool({
      name: "grades.whatif",
      description: "Pure GPA projection: apply hypothetical grades onto a transcript (replaces posted grades, fills unposted ones) and report per-term and cumulative GPAs.",
      parameters: Type.Unsafe({
        "type": "object",
        "properties": {
          "transcript": {
            "type": "object",
            "properties": {
              "terms": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "term": {
                      "type": "string"
                    },
                    "postedGpa": {
                      "type": "number"
                    },
                    "courses": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "course": {
                            "type": "string"
                          },
                          "credits": {
                            "type": "number"
                          },
                          "grade": {
                            "type": "string"
                          }
                        },
                        "required": [
                          "course",
                          "credits"
                        ]
                      }
                    }
                  },
                  "required": [
                    "term",
                    "courses"
                  ]
                }
              }
            },
            "required": [
              "terms"
            ]
          },
          "hypotheticals": {
            "default": [],
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "course": {
                  "type": "string"
                },
                "grade": {
                  "type": "string"
                }
              },
              "required": [
                "course",
                "grade"
              ]
            }
          }
        },
        "required": [
          "transcript"
        ]
      }),
      execute: async (params, config) =>
        operation("grades.whatif").handler(params as never, {
          config: config as Record<string, string | undefined>,
          dataDir: dataDir(),
        }),
    }),
    tool({
      name: "record.fetch",
      description: "The YES academic record: posted terms plus in-progress unposted courses. Fixture mode for development and tests; live mode gated on credentials.",
      parameters: Type.Unsafe({
        "type": "object",
        "properties": {
          "fixturePath": {
            "description": "Read the transcript from this JSON file instead of live YES (dev/test)",
            "type": "string"
          }
        }
      }),
      execute: async (params, config) =>
        operation("record.fetch").handler(params as never, {
          config: config as Record<string, string | undefined>,
          dataDir: dataDir(),
        }),
    }),
    tool({
      name: "sessions.forget",
      description: "Drop a cached session: removes the metadata row now; the vault-side value delete rides the OpenClaw wiring.",
      parameters: Type.Unsafe({
        "type": "object",
        "properties": {
          "idp": {
            "type": "string",
            "enum": [
              "vanderbilt",
              "microsoft"
            ]
          }
        },
        "required": [
          "idp"
        ]
      }),
      execute: async (params, config) =>
        operation("sessions.forget").handler(params as never, {
          config: config as Record<string, string | undefined>,
          dataDir: dataDir(),
        }),
    }),
    tool({
      name: "sessions.list",
      description: "Cached Vanderbilt SSO and Microsoft sessions: metadata only (idp, acquired, expiry, health). Session values never leave the vault.",
      parameters: Type.Unsafe({
        "type": "object",
        "properties": {}
      }),
      execute: async (params, config) =>
        operation("sessions.list").handler(params as never, {
          config: config as Record<string, string | undefined>,
          dataDir: dataDir(),
        }),
    }),
    tool({
      name: "sessions.open",
      description: "Injection payload for a cached session: raw Cookie header, CDP Network.setCookie params, or Playwright storageState. Gated: values resolve through the vault once the OpenClaw-side wiring lands.",
      parameters: Type.Unsafe({
        "type": "object",
        "properties": {
          "idp": {
            "type": "string",
            "enum": [
              "vanderbilt",
              "microsoft"
            ]
          },
          "format": {
            "default": "cookie-header",
            "type": "string",
            "enum": [
              "cookie-header",
              "cdp",
              "storage-state"
            ]
          }
        },
        "required": [
          "idp"
        ]
      }),
      execute: async (params, config) =>
        operation("sessions.open").handler(params as never, {
          config: config as Record<string, string | undefined>,
          dataDir: dataDir(),
        }),
    }),
    tool({
      name: "web",
      description: "Open this tool's web app: serves the operations page and the MCP endpoint on a free local port, opens a browser there, and returns the URL.",
      parameters: Type.Unsafe({
        "type": "object",
        "properties": {}
      }),
      execute: async (params, config) =>
        operation("web").handler(params as never, {
          config: config as Record<string, string | undefined>,
          dataDir: dataDir(),
        }),
    }),
  ],
});

/**
 * The web app, as a tab in the Control UI: one prefix route the gateway authenticates, handled
 * by the core package's own exported router — so `<prefix>/mcp` is answered in-process by the
 * same operations and everything else is the built page — and one descriptor that makes the
 * dashboard render it, instead of a URL an operator has to go and find.
 */
const WEB_PATH = "/plugins/vutoolkit/web";

const registerTools = entry.register;
entry.register = (api: OpenClawPluginApi) => {
  registerTools(api);
  api.registerHttpRoute({
    path: WEB_PATH,
    match: "prefix",
    // A Control UI tab may only point at a gateway-authenticated route, and the operator's
    // gateway session is the authentication — the page needs no pairing token of its own.
    auth: "gateway",
    // `env: false`: the Secrets panel writes the developer's `.env` in their checkout, and
    // this plugin runs in the gateway's working directory, not theirs.
    handler: handler({ path: `${WEB_PATH}/mcp`, prefix: WEB_PATH, env: false }),
  });
  const descriptor = {
    id: "vutoolkit-web",
    surface: "tab" as const,
    label: "Vutoolkit",
    path: `${WEB_PATH}/`,
  };
  // `api.session.controls` is the current facade and the top-level registrar its deprecated
  // alias; the plugin inspector's mock SDK has only the latter, so take whichever is there.
  const controls = api.session?.controls;
  if (controls) controls.registerControlUiDescriptor(descriptor);
  else api.registerControlUiDescriptor(descriptor);
};

// /tf:entry

export default entry;
