// tf:bg
// Generated by toolfactory. Do not edit this region; run `toolfactory build` to regenerate.
// Everything below the end marker is yours: the operations that need a browser live there.
import { browser } from "wxt/browser";
import { defineBackground } from "wxt/utils/define-background";
import { call, pair, paired, post, type McpRequest } from "../utils/mcp";

export type Message =
  | { type: "mcp"; request: McpRequest; endpoint?: string }
  | { type: "fetch"; request: McpRequest; endpoint?: string }
  | { type: "pair"; pairing: string }
  | { type: "paired" };

/**
 * The router: the one place a message reaches the kernel, and the only context holding the
 * token. `mcp` answers with the operation's result — what your capability code wants — and
 * `fetch` with the raw MCP response, which the generated page parses itself.
 */
export async function route(message: Message): Promise<unknown> {
  switch (message.type) {
    case "mcp":
      return await call(message.request, message.endpoint);
    case "fetch":
      return await post(message.request, message.endpoint);
    case "pair":
      return await pair(message.pairing);
    case "paired": {
      const { endpoint, token } = await paired();
      return { endpoint, token: Boolean(token) };
    }
  }
}

export const background = defineBackground(() => {
  browser.runtime.onMessage.addListener((message, _sender, sendResponse) => {
    route(message as Message).then(
      (value) => sendResponse({ value }),
      (error: unknown) =>
        sendResponse({ error: error instanceof Error ? error.message : String(error) }),
    );
    return true;
  });
});
// /tf:bg

// Yours: the operations that need a browser are implemented here, and survive every build.
// Decompose, don't inject (§4.5): the page state becomes JSON arguments, and the kernel runs the
// operation.
//
//   browser.runtime.onMessage.addListener(...)        // your own message types
//   await route({ type: "mcp", request: { method: "tools/call", params: { name: "…", arguments: {} } } })

export default background;
