// tf:content
// Generated by toolfactory. Do not edit this region; run `toolfactory build` to regenerate.
import { browser } from "wxt/browser";
import { defineContentScript } from "wxt/utils/define-content-script";
// /tf:content

// Yours: the shim that turns page state into JSON arguments. It runs inside the logged-in page,
// so the session is already there — read the DOM, hand the result to a portable operation, put
// the answer back. Never fetch the kernel from here: a content script's fetch uses the page's
// origin and is not CORS-exempt. Message the background worker instead, as below.
//
// This file is yours to keep working against the page it scrapes; a selector that moves is not
// something the generator can version-proof.
export default defineContentScript({
  matches: ["https://example.com/*"],
  async main() {
    const answer = await browser.runtime.sendMessage({
      type: "mcp",
      request: { method: "tools/call", params: { name: "…", arguments: {} } },
    });
    console.log("vutoolkit", answer);
  },
});
