// Generated by toolfactory. Do not edit; run `toolfactory build` to regenerate.
/**
 * `@web/*` is the `web` surface's component tree, resolved by the alias in `wxt.config.ts`. It
 * is declared here, not typechecked: `web`'s own build typechecks it, against its own React
 * types, and pulling it into this program would compile it against a second copy of them.
 */
declare module "@web/App" {
  const App: () => import("react").ReactNode;
  export default App;
}
