// Generated by toolfactory. Do not edit; run `toolfactory build` to regenerate.
import { defineConfig } from "vitest/config";
import { WxtVitest } from "wxt/testing/vitest-plugin";

// WxtVitest polyfills the extension APIs with @webext-core/fake-browser and applies the same
// aliases and auto-imports the build does, so a test imports an entrypoint like any module.
export default defineConfig({ plugins: [WxtVitest()] });
