// tf:config
// Generated by toolfactory. Do not edit this region; run `toolfactory build` to regenerate.
// Everything below the end marker is yours — merge into `generated` there and it survives a rebuild.
import { resolve } from "node:path";
import tailwindcss from "@tailwindcss/vite";
import { defineConfig } from "wxt";

/** Permissions only Chromium implements; dropped from every other target's manifest. */
export const CHROMIUM_ONLY = ["sidePanel", "debugger", "tabGroups"];
const CHROMIUM = ["chrome", "edge"];

const PERMISSIONS = ["storage", "activeTab"];
const HOST_PERMISSIONS = ["http://127.0.0.1/*", "http://localhost/*"];
const web = resolve(import.meta.dirname, "../../web/src");

export const generated = {
  modules: ["@wxt-dev/module-react"],
  // The release assets carry the tool's name, not this package's local one.
  zip: { name: "vutoolkit" },
  vite: () => ({
    plugins: [
      tailwindcss(),
      // The popup and the options page are the `web` surface's own component tree, imported
      // rather than duplicated. `enforce: "post"` is what makes this alias outrank WXT's own
      // `@` (this directory, still reachable as `~`), so that tree's internal `@/` imports
      // resolve inside it.
      {
        name: "toolfactory:web-alias",
        enforce: "post" as const,
        config: () => ({ resolve: { alias: { "@web": web, "@": web } } }),
      },
    ],
    resolve: { dedupe: ["react", "react-dom"] },
  }),
  // WXT emits one manifest per target from this: MV3 with a service worker for Chromium, MV2
  // with background scripts for Firefox and Safari, `host_permissions` folded into
  // `permissions` where the format has no such key.
  manifest: ({ browser }: { browser: string }) => ({
    name: "vutoolkit",
    permissions: PERMISSIONS.filter(
      (permission) => CHROMIUM.includes(browser) || !CHROMIUM_ONLY.includes(permission),
    ),
    host_permissions: HOST_PERMISSIONS,
    browser_specific_settings: {
      gecko: {
        id: "vutoolkit@GoatInAHat.github.io",
        // The floor for `storage.session` and for the data-collection key below.
        strict_min_version: "140.0",
        // Everything this extension sends goes to the kernel on this machine, so there is no
        // collection to declare. Change it if your operations ship user data to you.
        data_collection_permissions: { required: ["none"] },
      },
    },
    action: { default_title: "vutoolkit" },
  }),
};
// /tf:config

// Yours: everything below the end marker survives `toolfactory build`. Merge into the generated
// config — extra `modules`, an `srcDir`, manifest keys your capability code needs:
//   export default defineConfig({ ...generated, manifest: (env) => ({ ...generated.manifest(env), … }) })
export default defineConfig({ ...generated });
