// Generated by toolfactory. Do not edit; run `toolfactory build` to regenerate.
import { browser } from "wxt/browser";

/** Where `vutoolkit mcp --http` listens by default. */
export const DEFAULT_ENDPOINT = "http://127.0.0.1:3000/mcp";
/** MCP revision whose per-request `_meta` keys the kernel reads. */
export const MCP_PROTOCOL_VERSION = "2026-07-28";

export interface McpRequest {
  method: string;
  params: { name: string };
}

/** The paired kernel: its URL (persisted) and this session's token (in memory only). */
export async function paired(): Promise<{ endpoint: string; token?: string }> {
  const { endpoint } = await browser.storage.local.get("endpoint");
  const { token } = await browser.storage.session.get("token");
  return {
    endpoint: typeof endpoint === "string" && endpoint ? endpoint : DEFAULT_ENDPOINT,
    token: typeof token === "string" && token ? token : undefined,
  };
}

/**
 * Pair with `<url>#<token>`, the string `vutoolkit mcp --http --pair` prints. The
 * token is kept in `storage.session` — in memory, cleared when the browser closes, unreachable
 * from a content script — and never in `storage.local`.
 */
export async function pair(pairing: string): Promise<{ endpoint: string; token: boolean }> {
  const hash = pairing.indexOf("#");
  const endpoint = (hash < 0 ? pairing : pairing.slice(0, hash)).trim() || DEFAULT_ENDPOINT;
  const token = hash < 0 ? "" : pairing.slice(hash + 1).trim();
  await browser.storage.local.set({ endpoint });
  await browser.storage.session.set({ token });
  return { endpoint, token: Boolean(token) };
}

/**
 * One stateless MCP POST, from the background worker and nowhere else: an extension page's fetch
 * would carry no token, and a content script's is not CORS-exempt. A worker fetch to a
 * `host_permissions` host is, and sends no preflight, so the kernel needs no CORS middleware.
 */
export async function post(request: McpRequest, endpoint?: string): Promise<string> {
  const target = await paired();
  const url = endpoint && /^https?:/i.test(endpoint) ? endpoint : target.endpoint;
  let response: Response;
  try {
    response = await fetch(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Accept: "application/json, text/event-stream",
        "MCP-Protocol-Version": MCP_PROTOCOL_VERSION,
        "Mcp-Method": request.method,
        "Mcp-Name": request.params.name,
        ...(target.token ? { Authorization: `Bearer ${target.token}` } : {}),
      },
      body: JSON.stringify(request),
    });
  } catch (cause) {
    throw new Error(
      `${url} refused the connection: start \`vutoolkit mcp --http\`, and on Chromium make sure the browser is 144 or newer (Local Network Access exempts an extension that holds the host permission).`,
      { cause },
    );
  }
  return await response.text();
}

/** The same POST, parsed: plain JSON or the one `data:` SSE frame, exactly as the page reads it. */
export async function call(request: McpRequest, endpoint?: string): Promise<unknown> {
  const text = await post(request, endpoint);
  const framed = text.split("\n").find((line) => line.startsWith("data:"));
  let body: { error?: unknown; result?: { structuredContent?: unknown } };
  try {
    body = JSON.parse(framed ? framed.slice(5).trim() : text);
  } catch {
    throw new Error(`not an MCP response: ${text.slice(0, 500)}`);
  }
  if (body.error) throw new Error(JSON.stringify(body.error));
  return body.result?.structuredContent ?? body.result;
}
