// Generated by toolfactory. Do not edit; run `toolfactory build` to regenerate.
import { useEffect, useState, type ReactNode } from "react";
import { createRoot } from "react-dom/client";
import { browser } from "wxt/browser";

async function send(message: unknown): Promise<unknown> {
  const response = (await browser.runtime.sendMessage(message)) as
    | { value: unknown }
    | { error: string };
  if (response && "error" in response) throw new Error(response.error);
  return (response as { value: unknown })?.value;
}

/**
 * The page never fetches: every MCP POST is forwarded to the background worker, which holds the
 * paired endpoint and the token. That is what lets an extension page be the `web` surface's own
 * component tree, unchanged — and what keeps the credential out of a document.
 */
function bridgeFetch(): void {
  const direct = globalThis.fetch;
  globalThis.fetch = async (input, init) => {
    if (init?.method !== "POST") return direct(input, init);
    const endpoint =
      typeof input === "string" ? input : input instanceof URL ? input.href : input.url;
    const request = JSON.parse(String(init.body));
    const text = (await send({ type: "fetch", request, endpoint })) as string;
    return new Response(text, { headers: { "content-type": "application/json" } });
  };
}

/** Pairing: `<url>#<token>`, the string the kernel prints when it starts serving HTTP. */
export function Pairing() {
  const [pairing, setPairing] = useState("");
  const [status, setStatus] = useState("");
  const show = (state: { endpoint: string; token: boolean }) =>
    setStatus(`${state.endpoint}${state.token ? " (token held for this browser session)" : ""}`);
  useEffect(() => {
    send({ type: "paired" }).then((state) => show(state as { endpoint: string; token: boolean }));
  }, []);
  return (
    <form
      data-slot="pairing"
      style={{ display: "flex", gap: "0.5rem", alignItems: "center", padding: "0.5rem" }}
      onSubmit={(event) => {
        event.preventDefault();
        send({ type: "pair", pairing })
          .then((state) => show(state as { endpoint: string; token: boolean }))
          .catch((error: Error) => setStatus(error.message));
      }}
    >
      <input
        id="pairing"
        aria-label="Pairing string"
        placeholder="http://127.0.0.1:3000/mcp#token"
        style={{ flex: 1, minWidth: 0 }}
        value={pairing}
        onChange={(event) => setPairing(event.target.value)}
      />
      <button type="submit">Pair</button>
      <span data-slot="paired">{status}</span>
    </form>
  );
}

/**
 * The popup is the same page in 540 pixels; this is how it becomes a real one. `openOptionsPage`
 * is the WebExtension API for exactly that, and the options page already mounts this tree.
 */
export function OpenFullPage() {
  return (
    <button
      type="button"
      data-slot="open-full-page"
      style={{ marginLeft: "auto" }}
      onClick={() => browser.runtime.openOptionsPage()}
    >
      Open full page
    </button>
  );
}

export function mount(children: ReactNode): void {
  bridgeFetch();
  createRoot(document.getElementById("root") as HTMLElement).render(children);
}
