// Generated by toolfactory. Do not edit; run `toolfactory build` to regenerate.
import {
  Field,
  FieldDescription,
  FieldGroup,
  FieldLabel,
} from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import { Switch } from "@/components/ui/switch"
import { Textarea } from "@/components/ui/textarea"

export interface JsonSchema {
  type?: string
  description?: string
  enum?: (string | number)[]
  items?: { type?: string }
  properties?: Record<string, JsonSchema>
  required?: string[]
}

export type FieldValue = string | boolean | null
export type FormValues = Record<string, FieldValue>

type Control = "switch" | "select" | "number" | "list" | "json" | "text"

/** One control per property, chosen exactly as the generated CLI chooses a flag. */
function control(property: JsonSchema): Control {
  if (property.enum) return "select"
  if (property.type === "boolean") return "switch"
  if (property.type === "number" || property.type === "integer") return "number"
  if (property.type === "array") return property.items?.type === "string" ? "list" : "json"
  if (property.type === "string") return "text"
  return "json"
}

const HINT: Partial<Record<Control, string>> = {
  list: "comma-separated",
  json: "JSON",
}

function properties(schema: JsonSchema): [string, JsonSchema][] {
  return Object.entries(schema.properties ?? {})
}

export function initialValues(schema: JsonSchema): FormValues {
  return Object.fromEntries(
    properties(schema).map(([name, property]) => {
      const kind = control(property)
      return [name, kind === "switch" ? false : kind === "select" ? null : ""]
    }),
  )
}

/** The filled-in controls as JSON arguments, coerced the way the CLI coerces its flags. */
export function toArguments(schema: JsonSchema, values: FormValues): Record<string, unknown> {
  const entries = properties(schema).flatMap(([name, property]) => {
    const value = values[name]
    if (value === null || value === "") return []
    if (typeof value === "boolean") return value ? [[name, true] as const] : []
    switch (control(property)) {
      case "number":
        return [[name, Number(value)] as const]
      case "list":
        return [[name, value.split(",").map((item) => item.trim()).filter(Boolean)] as const]
      case "json":
        return [[name, JSON.parse(value) as unknown] as const]
      default:
        return [[name, value] as const]
    }
  })
  return Object.fromEntries(entries)
}

export function SchemaFields({
  schema,
  values,
  onChange,
  idPrefix,
}: {
  schema: JsonSchema
  values: FormValues
  onChange: (name: string, value: FieldValue) => void
  idPrefix: string
}) {
  const required = new Set(schema.required ?? [])
  return (
    <FieldGroup>
      {properties(schema).map(([name, property]) => {
        const kind = control(property)
        const id = `${idPrefix}-${name}`
        const hint = HINT[kind]
        const description = [property.description, hint && `(${hint})`].filter(Boolean).join(" ")
        const label = (
          <FieldLabel htmlFor={id}>
            {name}
            {required.has(name) ? <span className="text-destructive">*</span> : null}
          </FieldLabel>
        )
        const note = description ? <FieldDescription>{description}</FieldDescription> : null
        if (kind === "switch") {
          return (
            <Field key={name} orientation="horizontal">
              <Switch
                id={id}
                checked={values[name] === true}
                onCheckedChange={(checked) => onChange(name, checked)}
              />
              {label}
              {note}
            </Field>
          )
        }
        if (kind === "select") {
          const items = [
            { label: `Select ${name}`, value: null },
            ...(property.enum ?? []).map((option) => ({ label: String(option), value: String(option) })),
          ]
          return (
            <Field key={name}>
              {label}
              <Select
                items={items}
                value={values[name] as string | null}
                onValueChange={(value) => onChange(name, value as FieldValue)}
              >
                <SelectTrigger id={id}>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectGroup>
                    {items.map((item) => (
                      <SelectItem key={String(item.value)} value={item.value}>
                        {item.label}
                      </SelectItem>
                    ))}
                  </SelectGroup>
                </SelectContent>
              </Select>
              {note}
            </Field>
          )
        }
        if (kind === "json") {
          return (
            <Field key={name}>
              {label}
              <Textarea
                id={id}
                value={String(values[name] ?? "")}
                onChange={(event) => onChange(name, event.target.value)}
              />
              {note}
            </Field>
          )
        }
        return (
          <Field key={name}>
            {label}
            <Input
              id={id}
              type={kind === "number" ? "number" : "text"}
              value={String(values[name] ?? "")}
              onChange={(event) => onChange(name, event.target.value)}
            />
            {note}
          </Field>
        )
      })}
    </FieldGroup>
  )
}
