// Generated by toolfactory. Do not edit; run `toolfactory build` to regenerate.
import { spawn } from "node:child_process"
import { readFile } from "node:fs/promises"
import { chromium } from "playwright"

const page = JSON.parse(await readFile(new URL("./src/ops.json", import.meta.url), "utf8"))
const KERNEL = ["node","--import","tsx","src/toolfactory/mcp.ts"]
// A token of this run's own, so the smoke never depends on whether the author has paired, and
// the fragment-to-bearer path the page uses is what gets exercised.
const TOKEN = `smoke-${Math.random().toString(36).slice(2)}`

const kernel = spawn(KERNEL[0], [...KERNEL.slice(1), "--http", "0"], {
  stdio: ["ignore", "ignore", "pipe"],
  env: { ...process.env, "VUTOOLKIT_MCP_TOKEN": TOKEN },
})
const origin = await new Promise((resolve, reject) => {
  let output = ""
  kernel.stderr.setEncoding("utf8")
  kernel.stderr.on("data", (chunk) => {
    output += chunk
    const serving = /Serving MCP streamable HTTP on (\S+)/.exec(output)
    if (serving) resolve(new URL("/", serving[1]).href)
  })
  kernel.on("exit", (code) => reject(new Error(`the kernel exited with ${code}: ${output}`)))
})
console.log(`PASS the kernel serves ${origin}`)

// Read-only, because clicking Run here calls the real operation against the real project.
const operation = page.operations.find((candidate) => candidate.annotations?.readOnlyHint)
if (!operation) {
  console.log("PASS no read-only operation to round-trip; nothing to smoke")
  kernel.kill()
  process.exit(0)
}

const browser = await chromium.launch()
try {
  const tab = await browser.newPage()
  const failures = []
  tab.on("pageerror", (error) => failures.push(error.message))
  await tab.goto(`${origin}#${TOKEN}`)

  await tab.getByRole("button", { name: operation.name, exact: true }).click()
  const expected = Object.keys(operation.inputSchema.properties ?? {})
  for (const name of expected) {
    await tab.locator(`[id="${operation.name}-${name}"]`).waitFor({ state: "visible" })
  }
  console.log(`PASS ${operation.name} renders ${expected.length} field(s): ${expected.join(", ")}`)

  // Only a required plain string: anything with a default is already the value that works.
  const filled = (operation.inputSchema.required ?? []).find((name) => {
    const property = operation.inputSchema.properties[name]
    return property.type === "string" && !property.enum
  })
  if (filled) await tab.locator(`[id="${operation.name}-${filled}"]`).fill("smoke")

  await tab.getByRole("button", { name: "Run" }).click()

  if (page.cliAvailable) {
    const cli = tab.locator('pre[data-slot="cli"]')
    await cli.waitFor({ state: "visible" })
    const text = (await cli.textContent()).trim()
    if (filled && !text.includes(`"${filled}":"smoke"`)) {
      throw new Error(`cli preview lost the ${filled} argument: ${text}`)
    }
    console.log(`PASS cli preview: ${text}`)
  }

  // The round trip: same origin, bearer from the fragment, a real tools/call answered by the
  // kernel that served this page.
  await tab.getByRole("tab", { name: "Result" }).click()
  const result = tab.locator('pre[data-slot="result"]')
  await result.waitFor({ state: "visible" })
  if ((await result.getAttribute("data-failed")) === "true") {
    throw new Error(`${operation.name} failed: ${(await result.textContent()).trim()}`)
  }
  console.log(`PASS ${operation.name} round-tripped: ${(await result.textContent()).trim().slice(0, 200)}`)

  if (failures.length) throw new Error(`page raised: ${failures.join("; ")}`)
  console.log("PASS no uncaught page errors")
} finally {
  await browser.close()
  kernel.kill()
}
