// Generated by toolfactory. Do not edit; run `toolfactory build` to regenerate.
import path from "path"
import tailwindcss from "@tailwindcss/vite"
import react from "@vitejs/plugin-react"
import { defineConfig } from "vite"

// Where `<tool> mcp --http` listens. The dev server proxies /mcp there so the page POSTs
// same-origin (no CORS), and changeOrigin rewrites Host so the kernel's loopback guard passes.
const mcp = new URL(process.env.VITE_MCP_URL ?? "http://localhost:3000/mcp")

// https://vite.dev/config/
export default defineConfig({
  // Relative, so the one build is served the same wherever it is mounted: at "/" by
  // `mcp --http`, under a plugin route's prefix in the OpenClaw Control UI, and under
  // /<repo>/ on GitHub Pages. PAGES_BASE stays an override for a deployment that needs an
  // absolute one; the dev server is always "/".
  base: process.env.PAGES_BASE ?? "./",
  plugins: [react(), tailwindcss()],
  resolve: {
    alias: {
      "@": path.resolve(import.meta.dirname, "./src"),
    },
  },
  server: {
    proxy: {
      "/mcp": { target: mcp.origin, changeOrigin: true, rewrite: () => mcp.pathname },
    },
  },
})
